### ISSUE TITLE
Why you empty the project?

### ISSUE THREAD

**Issue by yycyyyc321** [DulyHao/AlphaForge#1]
I really admire you job, but now I can not see the code any more. If you can not share it as public project, can you send it to my email?
yc403426913@163.com, thanks a lot!

**Comment by JianboTang** [comment]
hello, Could you offer a copy of code for a little poor junior quant reseacher? my email is tangyao3669508@qq.com, Thank you very very very much!

**Comment by DulyHao** [comment]
Sorry for keep this repository empty so long, now we have published our code, please check it~
