### ISSUE TITLE
mismatch of returned values 

### ISSUE THREAD

**Issue by QuantML-Github** [DulyHao/AlphaForge#3]
thanks for the excellent work

I would like to bring a minor discrepancy to your attention. On line 171 of the train_AFF.py script, there appears to be a mismatch between the number of values expected and the number actually returned.

I guess it should be : 
data_all,data,data_valid,data_valid_withhead,data_test,data_test_withhead,_ = returned

**Comment by DulyHao** [comment]
Thank you very much, it should be a typo and we have repaired it.
