### ISSUE TITLE
Extra file required at the beginning of downloading data

### ISSUE THREAD

**Issue by zhaitongqing233** [DulyHao/AlphaForge#4]
It seems the fetching script require existence of .qlib/qlib_data/cn_data/instruments/all.txt

**Comment by Fs2qFtoS** [comment]
+1, same problem

**Comment by DulyHao** [comment]
have you already installed qlib first please?

**Comment by dbsyg** [comment]
csi300、csi500的数据集需要自己找吗

**Comment by DulyHao** [comment]
please refer to thq qlib official repository, you should be able to download the csi300 and csi500 component stocks through qlib.
