### ISSUE TITLE
Reason for picking operators

### ISSUE THREAD

**Issue by anxietymonger** [DulyHao/AlphaForge#5]
I believe you use the following operators in your implementation across different methods including your proposed method and the baselines:
```
unary_ops = [Inv, S_log1p]
binary_ops = [Add, Sub, Mul, Div, Pow,]
rolling_ops = [Ref, ts_mean, ts_sum, ts_std, ts_var, ts_max, ts_min,ts_med, ts_mad,ts_div, ts_pctchange, ts_delta, ts_wma, ts_ema,]
rolling_binary_ops = [ts_cov, ts_corr]
```

I can't stop wondering is there any specific reason of using these operators as the search space? For example, you
* picked s_log1p over normal log
* excluded some common operators seen in other literatures (e.g. rank, ts_rank, ts_product, ts_argmax, ts_argmin)
* implemented some operator but somehow didn't use them (e.g. Abs, Greater, Less, ts_skew, ts_kurt)

**Comment by anxietymonger** [comment]
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/10d24d9c-db05-4277-9d22-48657883d854">
In addition, in your work it seems different operators have been used from the original paper of your baseline. Is there any possibility that you could elaborate the reason?

**Comment by DulyHao** [comment]
The operators to be used is pretty important to the whole process, usually the more the better. We selected our our operators carefully and here are the reasons:
1: keep valid and prevent nan values: it is too easy for Log(x) to return a Nan value when x is lower than zero while S_log1p does not.
2: computational efficiency:  rank, ts_rank, ts_argmax, ts_argmin , these operators costs far more time than others and our experiments shows if these operators are included does not harm the performance.
3: prevent overffiting: Greater, Less, Abs, these kind operators are not continuous and will cause truncation, which means as long as you calculate enough times, it will return a factor with any possible stock rank you want. We believe this will cause overfitting.
4: keep discrimination: for example, ts_rank(x,20) will return a categorical value with 20 categories, when you need to rank 300 stocks, it is not enough and will cause IC and RankIC over-estimated.
5: promote predict-ability: we added some new operators according to our experiences, we believe these operators shall capture more information from the market and is a supplement to existing operators.

Thank you for your valuable question, if you have any other questions please let us know.

**Comment by DulyHao** [comment]
The operators to be used is pretty important to the whole process, usually the more the better. We selected our our operators carefully and here are the reasons:
1: keep valid and prevent nan values: it is too easy for Log(x) to return a Nan value when x is lower than zero while S_log1p does not.
2: computational efficiency:  rank, ts_rank, ts_argmax, ts_argmin , these operators costs far more time than others and our experiments shows if these operators are included does not harm the performance.
3: prevent overffiting: Greater, Less, Abs, these kind operators are not continuous and will cause truncation, which means as long as you calculate enough times, it will return a factor with any possible stock rank you want. We believe this will cause overfitting.
4: keep discrimination: for example, ts_rank(x,20) will return a categorical value with 20 categories, when you need to rank 300 stocks, it is not enough and will cause IC and RankIC over-estimated.
5: promote predict-ability: we added some new operators according to our experiences, we believe these operators shall capture more information from the market and is a supplement to existing operators.

Thank you for your valuable question, if you have any other questions please let us know.

**Comment by anxietymonger** [comment]
Thank you so much for the detailed explanation!
